---

- hosts: cloudstack_template
  gather_facts: no
  connection: local
  tasks:
    - name: "仮想マシンをストップ"
      cs_instance:
        name: "{{ inventory_hostname }}"
        zone: "{{ zone_name }}"
        state: stopped
      register: vm
    
    - name: "仮想マシンのROOTボリュームのIDを取得"
      shell: >
        cs listVolumes \
          type=ROOT \
          virtualmachineid={{ vm.id }} |
        jq -r ".volume[0]"
      changed_when: no
      register: volume
    
    - name: "ROOTボリュームのスナップショットを作成"
      shell: >
        cs createSnapshot \
          name={{ inventory_hostname }} \
          volumeid={{ (volume.stdout|from_json).id }}
    
    - name: "スナップショットからボリュームを作成"
      cs_volume:
        zone: "{{ zone_name }}"
        name: "{{ inventory_hostname }}"
        snapshot: "{{ inventory_hostname }}"
    
    - name: "ROOTボリュームのスナップショットを削除"
      shell: >
        cs listSnapshots \
          name={{ inventory_hostname }} |
        jq -r ".snapshot[]?.id" |
        xargs -I {} cs deleteSnapshot id={}
      register: res
      changed_when: res.stdout != ""
