---

- hosts: cloudstack
  connection: local
  tasks:
    - set_fact:
        vm_cache_dir: "{{ cache_dir + '/' + inventory_hostname }}"

    - name: "キャッシュ用ディレクトリの作成"
      file:
        path: "{{ vm_cache_dir }}"
        state: "directory"
        mode: "0755"

    - name: "SSH公開鍵の登録"
      cs_sshkeypair:
        name: "{{ inventory_hostname }}"
        public_key: "{{ lookup('file', ssh_public_key_file) }}"

    - name: "VMの作成"
      cs_instance:
        name: "{{ inventory_hostname }}"
        zone: "{{ zone_name }}"
        networks: ["{{ network_name }}"]
        service_offering: "{{ service_offering_name }}"
        template: "{{ template_name }}"
        ssh_key: "{{ inventory_hostname }}"
        state: started
      register: vm

    - name: "取得済みIPアドレスの確認"
      stat:
        path: "{{ vm_cache_dir + '/ip_address' }}"
      register: cache_ip_address

    - name: "新規IPアドレスの取得"
      cs_ip_address:
        zone: "{{ zone_name }}"
        network: "{{ network_name }}"
      register: ip_address
      when: not cache_ip_address.stat.exists

    - name: "取得したIPアドレスをキャッシュへ書き込み"
      copy:
        content: "{{ ip_address.ip_address }}"
        dest: "{{ vm_cache_dir + '/ip_address' }}"
      when: not cache_ip_address.stat.exists

    - name: "IPアドレスのキャッシュ読み込み"
      set_fact:
        ip_address: "{{ lookup('file', vm_cache_dir + '/ip_address') }}"

    - name: "ファイアウォールルールの設定"
      cs_firewall:
        zone: "{{ zone_name }}"
        ip_address: "{{ ip_address }}"
        protocol: "{{ item.protocol }}"
        start_port: "{{ item.start_port }}"
        end_port: "{{ item.end_port }}"
        cidr: "{{ item.cidr|default('0.0.0.0/0') }}"
      with_items: firewall_rules
    
    - name: "ポートフォワーディングルールの設定"
      cs_portforward:
        zone: "{{ zone_name }}"
        ip_address: "{{ ip_address }}"
        vm: "{{ vm.id }}"
        protocol: "{{ item.protocol }}"
        public_port: "{{ item.public_port }}"
        private_port: "{{ item.private_port }}"
      with_items: port_forwarding_rules
    
    - name: "SSHで接続可能になるまで待機"
      wait_for:
        host: "{{ ip_address }}"
        port: "{{ ansible_ssh_port|default(22) }}"
        search_regex: "OpenSSH"

    - name: "authorized_keysの設定に時間がかかる場合があるので余分に待機"
      pause: minutes=2
      when: vm|changed

