---

- hosts: cloud_init
  gather_facts: no
  pre_tasks:
    - include: tasks/set_ansible_ssh_host.yml
      vars:
        vm_name: "{{ inventory_hostname }}"
  roles:
    - role: cloud_init

- hosts: vagrant_box
  gather_facts: no
  pre_tasks:
    - include: tasks/set_ansible_ssh_host.yml
      vars:
        vm_name: "{{ inventory_hostname }}"
  roles:
    - role: vagrant_box

- hosts: redash
  gather_facts: no
  pre_tasks:
    - include: tasks/set_ansible_ssh_host.yml
      vars:
        vm_name: "{{ inventory_hostname }}"
  roles:
    - role: redash
